CarWashPOI/Areas/Administration/ViewModels/Locations/LocationForApprovalOutputModel.cs
namespace CarWashPOI.Areas.Administration.ViewModels.Locations
{
    public class LocationForApprovalOutputModel
    {
        public int Id { get; set; }

        public string Title { get; set; }
    }
}

CarWashPOI/ViewModels/Locations/AddLocationViewModel.cs
using CarWashPOI.ViewModels.LocationTypes;
using CarWashPOI.ViewModels.Towns;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace CarWashPOI.ViewModels.Locations
{
    public class AddLocationViewModel
    {

        [Required(ErrorMessage = "Полето Тип е задължително."), Display(Name = "Тип*")]
        public int LocationTypeId { get; set; }

        [Display(Name = "Име")]
        public string Title { get; set; }

        [Display(Name = "Описание")]
        public string Description { get; set; }

        [Required(ErrorMessage = "Полето Град е задължително."), Display(Name = "Град*")]
        public int TownId { get; set; }

        [Display(Name = "Район")]
        public string Neighbourhood { get; set; }

        [Display(Name = "Адрес")]
        public string Street { get; set; }

        [Required(ErrorMessage = "Локацията не е отбелязана с маркер на картата.")]
        public double? Latitude { get; set; }

        [Required]
        public double? Longitude { get; set; }

        [Display(Name = "Снимка")]
        public IFormFile Image { get; set; }

        public IEnumerable<LocationTypeViewModel> AllLocationTypes { get; set; }

        public IEnumerable<TownViewModel> AllTowns { get; set; }
    }
}

CarWashPOI/ViewModels/Locations/LocationDetailsOutputModel.cs
using CarWashPOI.ViewModels.Addresses;
using CarWashPOI.ViewModels.Comments;
using CarWashPOI.ViewModels.Ratings;
using System;
using System.Collections.Generic;

namespace CarWashPOI.ViewModels.Locations
{
    public class LocationDetailsOutputModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public string Description { get; set; }

        public string Type { get; set; }

        public LocationDetailsPageAddressOutputModel Address { get; set; }

        public RatingOutputModel Rating { get; set; }

        public DateTime AddedOn { get; set; }

        public string ImageUrl { get; set; }

        public IEnumerable<CommentOutputModel> Comments { get; set; }
    }
}

CarWashPOI/ViewModels/Locations/LocationOutputModel.cs
using CarWashPOI.ViewModels.Addresses;
using CarWashPOI.ViewModels.Ratings;
using System;

namespace CarWashPOI.ViewModels.Locations
{
    public class LocationOutputModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public HomePageAddressOutputModel Address { get; set; }

        public string ImageUrl { get; set; }

        public RatingOutputModel Rating { get; set; }

        public DateTime AddedOn { get; set; }

        public string TownAndNeighbourhood => string.Join(", ", Address.Town, Address.Neighbourhood).Trim(',', ' ');
    }
}

CarWashPOI/ViewModels/Locations/LocationRestResponseModel.cs
namespace CarWashPOI.ViewModels.Locations
{
    public class LocationRestResponseModel
    {
        public int Id { get; set; }

        public string Title { get; set; }

        public double Latitude { get; set; }

        public double Longitude { get; set; }
    }
}

CarWashPOI/Areas/Administration/Controllers/LocationsController.cs
using CarWashPOI.Services.Locations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CarWashPOI.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize(Roles = "Admin")]
    public class LocationsController : Controller
    {
        private readonly ILocationsService locationsService;

        public LocationsController(ILocationsService locationsService)
        {
            this.locationsService = locationsService;
        }

        public async Task<IActionResult> ForApproval(int id)
        {
            CarWashPOI.ViewModels.Locations.LocationDetailsOutputModel outputModel = await locationsService.GetLocationDetailsAsAdminAsync(id);

            return View(outputModel);
        }

        public async Task<IActionResult> Approve(int id)
        {
            int result = await locationsService.ApproveLocationAsync(id);

            if (result > 0)
            {
                TempData["locationApproved"] = true;
            }

            return RedirectToAction("Index", "Home", new { area = "Administration" });
        }

        public async Task<IActionResult> Delete(int id)
        {
            int result = await locationsService.DeleteLocationAsync(id);

            if (result > 0)
            {
                TempData["locationDeleted"] = true;
            }

            return RedirectToAction("Index", "Home", new { area = "Administration" });
        }
    }
}

CarWashPOI/Controllers/CommentsController.cs
using CarWashPOI.Data.Models;
using CarWashPOI.Services.Comments;
using CarWashPOI.ViewModels.Comments;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CarWashPOI.Controllers
{
    [Authorize]
    public class CommentsController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ICommentsService commentsService;

        public CommentsController(UserManager<ApplicationUser> userManager, ICommentsService commentsService)
        {
            this.userManager = userManager;
            this.commentsService = commentsService;
        }

        [HttpPost]
        public async Task<IActionResult> CommentLocation(CommentInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                TempData["commentSuccess"] = false;

                return LocalRedirect($"/Locations/{inputModel.LocationId}#commentSuccess");
            }

            inputModel.UserId = userManager.GetUserId(User);

            int result = await commentsService.AddLocationCommentAsync(inputModel);

            if (result > 0)
            {
                TempData["commentSuccess"] = true;
            }

            return LocalRedirect($"/Locations/{inputModel.LocationId}#commentSuccess");
        }
    }
}

CarWashPOI/Controllers/LocationsController.cs
using CarWashPOI.Services.Locations;
using CarWashPOI.Services.LocationTypes;
using CarWashPOI.Services.Towns;
using CarWashPOI.ViewModels.Locations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace CarWashPOI.Controllers
{
    public class LocationsController : Controller
    {
        private readonly ILocationsService locationsService;
        private readonly ITownsService townsService;
        private readonly ILocationTypesService locationTypesService;

        public LocationsController(ILocationsService locationsService, ITownsService townsService,
            ILocationTypesService locationTypesService)
        {
            this.locationsService = locationsService;
            this.townsService = townsService;
            this.locationTypesService = locationTypesService;
        }

        [Route("/Locations/{id:int}")]
        public async Task<IActionResult> LocationDetails(int id)
        {
            LocationDetailsOutputModel outputModel = await locationsService.GetLocationDetailsAsUserAsync(id);
            outputModel.Comments = outputModel.Comments.OrderByDescending(c => c.AddedOn);

            return View(outputModel);
        }

        [Authorize]
        public async Task<IActionResult> Add()
        {
            AddLocationViewModel addLocationViewModel = new AddLocationViewModel
            {
                AllLocationTypes = await locationTypesService.GetAllLocationTypesAsync(),
                AllTowns = await townsService.GetAllTownsAsync()
            };

            return View(addLocationViewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(AddLocationViewModel addLocationViewModel)
        {
            if (!ModelState.IsValid)
            {
                addLocationViewModel.AllLocationTypes = await locationTypesService.GetAllLocationTypesAsync();
                addLocationViewModel.AllTowns = await townsService.GetAllTownsAsync();

                return View(addLocationViewModel);
            }

            int locationId = await locationsService.AddAsync(addLocationViewModel);
            if (locationId > 0)
            {
                TempData["locationAdded"] = true;
            }

            return LocalRedirect("/#locationAdded");
        }
    }
}

CarWashPOI/Views/Locations/Add.cshtml
@model CarWashPOI.ViewModels.Locations.AddLocationViewModel

@{
    ViewData["Title"] = "ДОБАВИ НОВА ЛОКАЦИЯ";
}

<h6 class="text-secondary my-2 text-center">Намерете локацията на картата и я отбележете като кликнете с мишката, след това попълнете формата по-долу.</h6>
<div class="text-center mb-2">
    <span asp-validation-for="Latitude" class="text-danger"></span>
</div>
<div id="map" class="mb-4"></div>

<div class="col-md-4 mx-auto justify-content-center text-center">
    <hr />
    <form asp-antiforgery="true" asp-controller="Locations" asp-action="Add" enctype="multipart/form-data" method="post">
        <input id="latitude" asp-for="@Model.Latitude" hidden />
        <input id="longitude" asp-for="@Model.Longitude" hidden />
        <div class="form-group">
            <label asp-for="@Model.LocationTypeId"></label>
            <select asp-for="@Model.LocationTypeId" class="custom-select">
                <option value="" selected></option>
                @foreach (var locationType in Model.AllLocationTypes)
                {
                    <option value="@locationType.Id">@locationType.Type</option>
                }
            </select>
            <span asp-validation-for="LocationTypeId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Title"></label>
            <input asp-for="@Model.Title" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="@Model.Description"></label>
            <textarea asp-for="@Model.Description" class="form-control" rows="5"></textarea>
        </div>
        <div class="form-group">
            <label asp-for="@Model.TownId"></label>
            <select asp-for="@Model.TownId" class="custom-select">
                <option value="" selected></option>
                @foreach (var town in Model.AllTowns)
                {
                    <option value="@town.Id">@town.Name</option>
                }
            </select>
            <span asp-validation-for="TownId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Neighbourhood"></label>
            <input asp-for="@Model.Neighbourhood" class="form-control" />
            <span asp-validation-for="@Model.Neighbourhood" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.Street"></label>
            <input asp-for="@Model.Street" class="form-control" />
        </div>
        <label asp-for="@Model.Image"></label>
        <div class="custom-file">
            <input asp-for="@Model.Image" type="file" id="customFile" class="custom-file-input">
            <label id="customFileLabel" class="custom-file-label" for="customFile">Избери файл</label>
        </div>
        <p class="text-muted mt-3">(полетата отбелязани с * са задължителни)</p>
        <button type="submit" class="btn btn-success mt-2">ДОБАВИ ЛОКАЦИЯТА</button>
    </form>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <partial name="MapIncludesPartial" />
    <partial name="AddLocationMapJsPartial" />
    <partial name="UpdateFileUploadLabelJsPartial" />
}

CarWashPOI/Views/Locations/AddLocationMapJsPartial.cshtml
<script>
    $(document).ready(drawMap);

    function drawMap() {
        let map = L.map("map").setView([42.7510, 25.2379], 8);

        L.tileLayer("https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}", {
            maxZoom: 21,
            id: "mapbox/streets-v11",
            tileSize: 512,
            zoomOffset: -1,
            accessToken: "pk.eyJ1IjoidnplaGlyZXYiLCJhIjoiY2s3NGpvNGJsMDYwcDNmbzNqZXM2enM4MiJ9.XENUDCk7i7evvkHshJjKUg",
        })
            .addTo(map);

        let marker = L.marker();

        map.on("click", onMapClick);

        function onMapClick(e) {
            marker.setLatLng(e.latlng).addTo(map);
            $("#latitude").val(e.latlng.lat);
            $("#longitude").val(e.latlng.lng);
        }
    }
</script>

CarWashPOI/Views/Locations/LocationDetails.cshtml
@model CarWashPOI.ViewModels.Locations.LocationDetailsOutputModel

@{
    ViewData["Title"] = Model.Title;
}

<div id="map" class="mb-4"></div>

<input type="hidden" id="locationId" value="@Model.Id">

<h4 class="text-center mx-auto">@Model.Title</h4>

<div class="row justify-content-center text-center mw-100">
    <div class="card border-success m-3 col-md-4 p-0" style="max-width: 20rem;">
        <div class="card-header p-1">ОЦЕНКА</div>
        <div class="card-body p-1">
            <h4 class="card-title mt-2">
                <button id="positiveRating" class="btn btn-success mr-2">+ @Model.Rating.Positives</button>
                /
                <button id="negativeRating" class="btn btn-danger ml-2">- @Model.Rating.Negatives</button>
            </h4>
            <span id="rateMessage" class="text-warning"></span>
        </div>
    </div>
    <div class="card border-success m-3  col-md-4 p-0" style="max-width: 20rem;">
        <div class="card-header p-1">ТИП</div>
        <div class="card-body p-1">
            <h4 class="card-title">@Model.Type</h4>
        </div>
    </div>
    <div class="card border-success m-3 col-md-4 p-0" style="max-width: 20rem;">
        <div class="card-header p-1">ГРАД</div>
        <div class="card-body p-1">
            <h4 class="card-title">@Model.Address.Town</h4>
        </div>
    </div>
    @if (Model.Address != null && Model.Address.Neighbourhood != null)
    {
        <div class="card border-success m-3 col-md-4 p-0" style="max-width: 20rem;">
            <div class="card-header p-1">РАЙОН</div>
            <div class="card-body p-1">
                <h4 class="card-title">@Model.Address.Neighbourhood</h4>
            </div>
        </div>
    }
    @if (Model.Address != null && Model.Address.Street != null)
    {
        <div class="card border-success m-3 col-md-4 p-0" style="max-width: 20rem;">
            <div class="card-header p-1">АДРЕС</div>
            <div class="card-body p-1">
                <h4 class="card-title">@Model.Address.Street</h4>
            </div>
        </div>
    }
    <div class="card border-success m-3 col-md-4 p-0" style="max-width: 20rem;">
        <div class="card-header p-1">ДОБАВЕНА</div>
        <div class="card-body p-1">
            <h4 class="card-title">@Model.AddedOn.ToString("dd-MMM-yyyy")</h4>
        </div>
    </div>
</div>

@if (Model.Description != null)
{
    <div class="row justify-content-center text-center font-italic mb-4 mx-auto" style="max-width: 75%">
        <h4>@Model.Description</h4>
    </div>
}
@if (Model.ImageUrl != null)
{
    <div class="row justify-content-center text-center mw-100 mb-3">
        <img class="border border-success rounded w-50" src="@Model.ImageUrl" />
    </div>
}

<div id="commentSuccess" class="row justify-content-center mw-100">
    @if (TempData["commentSuccess"] as bool? == true)
    {
        <div class="alert alert-dismissible alert-success col-md-4 text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            Коментарът е добавен успешно.
        </div>
    }
    else if (TempData["commentSuccess"] as bool? == false)
    {
        <div class="alert alert-dismissible alert-danger col-md-4 text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            Коментарът трябва да е с дължина от минимум 3 символа и/или възникна грешка.
        </div>
    }
</div>

<div id="comments" class="row mw-100 justify-content-center">
    @foreach (var comment in Model.Comments)
    {
        <div class="col-md-4 toast show m-3">
            <div class="toast-header">
                <strong class="mr-auto">@comment.Author</strong>
                <small>@comment.AddedOn.ToString("dd-MMM-yyyy")</small>
            </div>
            <div class="toast-body">
                @comment.Content
            </div>
        </div>
    }
</div>

@if (User.Identity.IsAuthenticated)
{
    <form asp-antiforgery="true" asp-controller="Comments" asp-action="CommentLocation" method="post">
        <div class="row mw-100 justify-content-center text-center mt-3">
            <div class="form-group col-md-4">
                <input type="hidden" name="locationId" value="@Model.Id">
                <textarea name="content" class="form-control mb-3" rows="3" placeholder="Вашият коментар..."></textarea>
                <button type="submit" class="btn btn-success">КОМЕНТИРАЙ</button>
            </div>
        </div>
    </form>
}
else
{
    <p class="text-muted text-center">(само логнати потребители могат да коментират)</p>

}

@section Scripts {
    <partial name="MapIncludesPartial" />
    <partial name="LocationDetailsMapJsPartial" />
    <partial name="RateLocationJsPartial" />
}

CarWashPOI/Views/Locations/RateLocationJsPartial.cshtml
<script>
    let positiveRatingElement = $("#positiveRating");
    let negativeRatingElement = $("#negativeRating");

    positiveRatingElement.click(function () {
        rateLocation(locationId, true);
    });

    negativeRatingElement.click(function () {
        rateLocation(locationId, false);
    });

    function rateLocation(locationId, isPositive) {
        $.ajax({
            method: "POST",
            url: `/Rest/Rate/${locationId}`,
            data: { isPositive: isPositive }
        })
            .done(function (response) {
                positiveRatingElement.text(`+ ${response.positives}`);
                negativeRatingElement.text(`- ${response.negatives}`);
            })
            .fail(function (xhr) {
                if (xhr.status === 401) {
                    $("#rateMessage").text("(само логнати потребители могат да оценят)");
                    setTimeout(function () { $("#rateMessage").text("") }, 3000);
                }
            });
    }
</script>