CarWashPOI/Areas/Administration/Controllers/HomeController.cs
using CarWashPOI.Areas.Administration.ViewModels;
using CarWashPOI.Services.Articles;
using CarWashPOI.Services.Locations;
using CarWashPOI.Services.Users;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace CarWashPOI.Areas.Administration.Controllers
{
    [Area("Administration")]
    [Authorize(Roles = "Admin")]
    public class HomeController : Controller
    {
        private readonly IArticlesService articlesService;
        private readonly ILocationsService locationsService;
        private readonly IUsersService usersService;

        public HomeController(IArticlesService articlesService,
            ILocationsService locationsService,
            IUsersService usersService)
        {
            this.articlesService = articlesService;
            this.locationsService = locationsService;
            this.usersService = usersService;
        }
        public async Task<IActionResult> Index()
        {
            AdministrationIndexOutputModel outputModel = new AdministrationIndexOutputModel
            {
                LocationsForApproval = await locationsService.GetNonApprovedLocationsAsync(),
                ArticlesForApproval = await articlesService.GetNonApprovedArticlesAsync(),
                TotalLocations = await locationsService.GetTotalLocationsAsync(),
                TotalArticles = await articlesService.GetTotalArticlesAsync(),
                TotalUsers = await usersService.GetTotalUsersAsync(),
            };

            return View(outputModel);
        }
    }
}

CarWashPOI/Controllers/ArticlesController.cs
using CarWashPOI.Data.Models;
using CarWashPOI.Services.Articles;
using CarWashPOI.ViewModels.Articles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace CarWashPOI.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly IArticlesService articlesService;
        private readonly UserManager<ApplicationUser> userManager;

        public ArticlesController(IArticlesService articlesService, UserManager<ApplicationUser> userManager)
        {
            this.articlesService = articlesService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index(int page, string orderBy)
        {
            const int ResultsPerPage = 10;

            if (page < 1)
            {
                page = 1;
            }

            int skip = (page - 1) * ResultsPerPage;

            ArticlesIndexOutputModel outputModel = await articlesService.GetArticlesAsync(skip, ResultsPerPage, orderBy);

            if (outputModel.AllArticles == 0)
            {
                return View(outputModel);
            }

            int lastPage = (int)Math.Ceiling(((double)outputModel.AllArticles / ResultsPerPage));

            if (page > lastPage)
            {
                page = lastPage;

                return RedirectToAction(nameof(Index), outputModel);
            }

            outputModel.CurrentPage = page;
            outputModel.LastPage = lastPage;

            return View(outputModel);
        }

        [Authorize]
        public IActionResult Add()
        {
            return View();
        }

        [Route("/Articles/{articleId:int}")]
        public async Task<IActionResult> ReadArticle(int articleId)
        {
            ReadArticleOutputModel article = await articlesService.GetArticleByIdAsUserAsync(articleId);

            return View(article);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(AddArticleViewModel inputModel)
        {
            inputModel.UserId = userManager.GetUserId(User);

            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            int articleId = await articlesService.AddArticleAsync(inputModel);

            if (articleId > 0)
            {
                TempData["articleAdded"] = true;
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CarWashPOI/Controllers/HomeController.cs
using CarWashPOI.Services.Locations;
using CarWashPOI.Services.LocationTypes;
using CarWashPOI.Services.Towns;
using CarWashPOI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;
using System.Threading.Tasks;

namespace CarWashPOI.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILocationsService locationsService;
        private readonly ITownsService townsService;
        private readonly ILocationTypesService locationTypesService;

        public HomeController(ILocationsService locationsService, ITownsService townsService, ILocationTypesService locationTypesService)
        {
            this.locationsService = locationsService;
            this.townsService = townsService;
            this.locationTypesService = locationTypesService;
        }

        public async Task<IActionResult> Index(HomePageInputModel inputModel)
        {
            const int ResultsPerPage = 9;

            if (inputModel.Page < 1)
            {
                inputModel.Page = 1;
            }

            int skip = (inputModel.Page - 1) * ResultsPerPage;

            HomePageOutputModel homePageOutputModel = await locationsService.GetLocationsAsync(
                    inputModel.TownId,
                    inputModel.TypeId,
                    inputModel.OrderBy,
                    skip,
                    ResultsPerPage);

            homePageOutputModel.AllTowns = await townsService.GetAllTownsAsync();
            homePageOutputModel.AllTypes = await locationTypesService.GetAllLocationTypesAsync();
            homePageOutputModel.SelectedTownId = inputModel.TownId;
            homePageOutputModel.SelectedTypeId = inputModel.TypeId;
            homePageOutputModel.SelectedOrderBy = inputModel.OrderBy;

            if (homePageOutputModel.AllLocations == 0)
            {
                return View(homePageOutputModel);
            }

            int lastPage = (int)Math.Ceiling(((double)homePageOutputModel.AllLocations / ResultsPerPage));

            if (inputModel.Page > lastPage)
            {
                inputModel.Page = lastPage;

                return RedirectToAction(nameof(Index), inputModel);
            }

            homePageOutputModel.CurrentPage = inputModel.Page;
            homePageOutputModel.LastPage = lastPage;

            return View(homePageOutputModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel
            {
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            });
        }
    }
}

CarWashPOI/Controllers/LocationsController.cs
using CarWashPOI.Services.Locations;
using CarWashPOI.Services.LocationTypes;
using CarWashPOI.Services.Towns;
using CarWashPOI.ViewModels.Locations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace CarWashPOI.Controllers
{
    public class LocationsController : Controller
    {
        private readonly ILocationsService locationsService;
        private readonly ITownsService townsService;
        private readonly ILocationTypesService locationTypesService;

        public LocationsController(ILocationsService locationsService, ITownsService townsService,
            ILocationTypesService locationTypesService)
        {
            this.locationsService = locationsService;
            this.townsService = townsService;
            this.locationTypesService = locationTypesService;
        }

        [Route("/Locations/{id:int}")]
        public async Task<IActionResult> LocationDetails(int id)
        {
            LocationDetailsOutputModel outputModel = await locationsService.GetLocationDetailsAsUserAsync(id);
            outputModel.Comments = outputModel.Comments.OrderByDescending(c => c.AddedOn);

            return View(outputModel);
        }

        [Authorize]
        public async Task<IActionResult> Add()
        {
            AddLocationViewModel addLocationViewModel = new AddLocationViewModel
            {
                AllLocationTypes = await locationTypesService.GetAllLocationTypesAsync(),
                AllTowns = await townsService.GetAllTownsAsync()
            };

            return View(addLocationViewModel);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(AddLocationViewModel addLocationViewModel)
        {
            if (!ModelState.IsValid)
            {
                addLocationViewModel.AllLocationTypes = await locationTypesService.GetAllLocationTypesAsync();
                addLocationViewModel.AllTowns = await townsService.GetAllTownsAsync();

                return View(addLocationViewModel);
            }

            int locationId = await locationsService.AddAsync(addLocationViewModel);
            if (locationId > 0)
            {
                TempData["locationAdded"] = true;
            }

            return LocalRedirect("/#locationAdded");
        }
    }
}

CarWashPOI/Areas/Administration/Views/Home/Index.cshtml
@model CarWashPOI.Areas.Administration.ViewModels.AdministrationIndexOutputModel

@{
    ViewData["Title"] = "АДМИНИСТРАЦИЯ";
}

<h1 class="text-center mx-auto my-3">@ViewData["Title"]</h1>

<div class="row justify-content-center mw-100">
    @if (TempData["articleApproved"] as bool? == true)
    {
        <div class="alert alert-dismissible alert-success col-md-4 text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            Статията беше одобрена успешно.
        </div>
    }
    @if (TempData["articleDeleted"] as bool? == true)
    {
        <div class="alert alert-dismissible alert-success col-md-4 text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            Статията беше изтрита успешно.
        </div>
    }
    @if (TempData["locationApproved"] as bool? == true)
    {
        <div class="alert alert-dismissible alert-success col-md-4 text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            Локацията беше одобрена успешно.
        </div>
    }
    @if (TempData["locationDeleted"] as bool? == true)
    {
        <div class="alert alert-dismissible alert-success col-md-4 text-center">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            Локацията беше изтрита успешно.
        </div>
    }
</div>

<div class="row justify-content-center mx-auto">
    <div class="col-md-4">
        <table class="table table-hover">
            <thead>
                <tr class="table-active">
                    <th scope="col">ЛОКАЦИИ ЗА ОДОБРЕНИЕ</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.LocationsForApproval.Count() == 0)
                {
                    <tr class="table-default">
                        <th scope="row">Няма резултати.</th>
                        <td></td>
                    </tr>
                }

                @foreach (var location in Model.LocationsForApproval)
                {
                    <tr class="table-default">
                        <th scope="row">@location.Title</th>
                        <td><a asp-area="Administration" asp-controller="Locations" asp-action="ForApproval" asp-route-id="@location.Id" class="btn btn-primary">ОТВОРИ</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

    <div class="col-md-4">
        <table class="table table-hover">
            <thead>
                <tr class="table-active">
                    <th scope="col">СТАТИИ ЗА ОДОБРЕНИЕ</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @if (Model.ArticlesForApproval.Count() == 0)
                {
                    <tr class="table-default">
                        <th scope="row">Няма резултати.</th>
                        <td></td>
                    </tr>
                }
                @foreach (var article in Model.ArticlesForApproval)
                {
                    <tr class="table-default">
                        <th scope="row">@article.Title</th>
                        <td><a asp-area="Administration" asp-controller="Articles" asp-action="ForApproval" asp-route-id="@article.Id" class="btn btn-primary">ОТВОРИ</a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div class="col-md-4 mx-auto">
    <table class="table table-hover">
        <tbody>
            <tr class="table-default">
                <th scope="row">ЛОКАЦИИ В САЙТА</th>
                <td>@Model.TotalLocations</td>
            </tr>
            <tr class="table-default">
                <th scope="row">СТАТИИ В САЙТА</th>
                <td>@Model.TotalArticles</td>
            </tr>
            <tr class="table-default">
                <th scope="row">БРОЙ РЕГИСТРИРАНИ ПОТРЕБИТЕЛИ</th>
                <td>@Model.TotalUsers</td>
            </tr>
        </tbody>
    </table>
</div>