CarWashPOI/Controllers/ArticlesController.cs
using CarWashPOI.Data.Models;
using CarWashPOI.Services.Articles;
using CarWashPOI.ViewModels.Articles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace CarWashPOI.Controllers
{
    public class ArticlesController : Controller
    {
        private readonly IArticlesService articlesService;
        private readonly UserManager<ApplicationUser> userManager;

        public ArticlesController(IArticlesService articlesService, UserManager<ApplicationUser> userManager)
        {
            this.articlesService = articlesService;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index(int page, string orderBy)
        {
            const int ResultsPerPage = 10;

            if (page < 1)
            {
                page = 1;
            }

            int skip = (page - 1) * ResultsPerPage;

            ArticlesIndexOutputModel outputModel = await articlesService.GetArticlesAsync(skip, ResultsPerPage, orderBy);

            if (outputModel.AllArticles == 0)
            {
                return View(outputModel);
            }

            int lastPage = (int)Math.Ceiling(((double)outputModel.AllArticles / ResultsPerPage));

            if (page > lastPage)
            {
                page = lastPage;

                return RedirectToAction(nameof(Index), outputModel);
            }

            outputModel.CurrentPage = page;
            outputModel.LastPage = lastPage;

            return View(outputModel);
        }

        [Authorize]
        public IActionResult Add()
        {
            return View();
        }

        [Route("/Articles/{articleId:int}")]
        public async Task<IActionResult> ReadArticle(int articleId)
        {
            ReadArticleOutputModel article = await articlesService.GetArticleByIdAsUserAsync(articleId);

            return View(article);
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(AddArticleViewModel inputModel)
        {
            inputModel.UserId = userManager.GetUserId(User);

            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            int articleId = await articlesService.AddArticleAsync(inputModel);

            if (articleId > 0)
            {
                TempData["articleAdded"] = true;
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CarWashPOI/Controllers/SiteInfoController.cs
using CarWashPOI.Services.Emails;
using CarWashPOI.ViewModels.SiteInfo;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System.IO;
using System.Threading.Tasks;

namespace CarWashPOI.Controllers
{
    public class SiteInfoController : Controller
    {
        private readonly IWebHostEnvironment env;
        private readonly IConfiguration configuration;
        private readonly IEmailsService emailsService;

        public SiteInfoController(IWebHostEnvironment env, IConfiguration configuration, IEmailsService emailsService)
        {
            this.env = env;
            this.configuration = configuration;
            this.emailsService = emailsService;
        }

        public async Task<IActionResult> PrivacyPolicy()
        {
            string filePath = env.ContentRootPath + Path.DirectorySeparatorChar + "privacyPolicy.txt";
            PrivacyOutputModel outputModel = new PrivacyOutputModel
            {
                Content = await System.IO.File.ReadAllTextAsync(filePath),
            };

            return View(outputModel);
        }

        public async Task<IActionResult> TermsAndConditions()
        {
            string filePath = env.ContentRootPath + Path.DirectorySeparatorChar + "termsAndConditions.txt";
            TermsAndConditionsOutputModel outputModel = new TermsAndConditionsOutputModel
            {
                Content = await System.IO.File.ReadAllTextAsync(filePath),
            };

            return View(outputModel);
        }

        public IActionResult ContactUs()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ContactUs(ContactUsInputModel inputModel)
        {
            if (!ModelState.IsValid)
            {
                return View(inputModel);
            }

            SendGrid.Response result = await emailsService
                .SendAsync(configuration["SendGrid:To"], $"From: {inputModel.Email}", inputModel.Message);

            if (result.StatusCode.ToString() == "Accepted")
            {
                TempData["contact"] = true;

                return RedirectToAction(nameof(ContactUs));
            }
            else
            {
                TempData["contact"] = false;

                return View(inputModel);
            }

        }
    }
}

CarWashPOI/Views/Shared/LocationDetailsMapJsPartial.cshtml
<script>
    let locationId = $("#locationId").val();

    $.ajax({
        url: `/Rest/Locations/${locationId}`,
    })
        .done(function (locationCoordinates) {
            drawMap(locationCoordinates);
        });

    function drawMap(locationCoordinates) {
        let map = L.map("map").setView([locationCoordinates.latitude, locationCoordinates.longitude], 17);

        L.tileLayer("https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}", {
            maxZoom: 21,
            id: "mapbox/streets-v11",
            tileSize: 512,
            zoomOffset: -1,
            accessToken: "pk.eyJ1IjoidnplaGlyZXYiLCJhIjoiY2s3NGpvNGJsMDYwcDNmbzNqZXM2enM4MiJ9.XENUDCk7i7evvkHshJjKUg",
        })
            .addTo(map);

        let marker = L.marker([locationCoordinates.latitude, locationCoordinates.longitude]);
        marker.addTo(map);
    }
</script>

CarWashPOI/Views/Shared/MapIncludes.cshtml
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
      integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
      crossorigin="" />

<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
        integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
        crossorigin="">
</script>

CarWashPOI/Views/Shared/MapIncludesPartial.cshtml
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css"
      integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
      crossorigin="" />

<script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"
        integrity="sha512-gZwIG9x3wUXg2hdXF6+rVkLF/0Vi9U8D2Ntg4Ga5I5BZpVkVxlJWbSQtXPSiUTtC0TjtGOmxa1AJPuV0CPthew=="
        crossorigin="">
</script>

CarWashPOI/Views/Shared/UpdateFileUploadLabelJsPartial.cshtml
<script>
    $("#customFile").on("change", updateFilesCount);

    function updateFilesCount() {
        let filesCount = Array.from($(this)[0].files).length;

        let message = filesCount === 1 ? `${filesCount} избран файл` : `${filesCount} избрани файла`;
        $("#customFileLabel").addClass("selected").html(message);
    }
</script>

CarWashPOI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarWashPOI</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom py-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img id="siteLogo" class="mr-3" src="~/img/siteLogo.png" />CarWashPOI</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link siteNav" asp-area="" asp-controller="Home" asp-action="Index">НАЧАЛО</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link siteNav" asp-area="" asp-controller="Articles" asp-action="Index">БЛОГ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link siteNav" asp-area="" asp-controller="SiteInfo" asp-action="ContactUs">КОНТАКТ</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mx-0 px-0">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CarWashPOI™ - <a asp-area="" asp-controller="SiteInfo" asp-action="PrivacyPolicy">Политика за поверителност</a> - <a asp-area="" asp-controller="SiteInfo" asp-action="TermsAndConditions">Правила за ползване</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>